"""Constants for Daylight Calendar Import."""

DOMAIN = "daylight_calendar_import"
CONF_AI_TASK_ENTITY = "ai_task_entity"
CONF_CALENDAR_ENTITY = "calendar_entity"
SERVICE_PARSE_TEXT = "parse_text"
SERVICE_IMPORT_TEXT = "import_text"
SERVICE_SUBMIT_TEXT = "submit_text"
SERVICE_APPROVE_PENDING = "approve_pending"
SERVICE_REJECT_PENDING = "reject_pending"
ATTR_TEXT = "text"
ATTR_SOURCE_ID = "source_id"
ATTR_PENDING_ID = "pending_id"
