"""Constants for Daylight Calendar Import."""

DOMAIN = "daylight_calendar_import"
CONF_AI_TASK_ENTITY = "ai_task_entity"
CONF_CALENDAR_ENTITY = "calendar_entity"
CONF_CALENDAR_ENTITIES = "calendar_entities"
SERVICE_PARSE_TEXT = "parse_text"
SERVICE_IMPORT_TEXT = "import_text"
SERVICE_SUBMIT_TEXT = "submit_text"
SERVICE_SUBMIT_IMAGE = "submit_image"
SERVICE_SUBMIT_PDF = "submit_pdf"
SERVICE_APPROVE_PENDING = "approve_pending"
SERVICE_REJECT_PENDING = "reject_pending"
SERVICE_LIST_PENDING = "list_pending"
SERVICE_LIST_ACTIVITY = "list_activity"
SERVICE_GET_ACTIVITY = "get_activity"
SERVICE_GET_PENDING = "get_pending"
SERVICE_GET_PENDING_EVENT = "get_pending_event"
SERVICE_EDIT_PENDING_EVENT = "edit_pending_event"
SERVICE_REJECT_PENDING_EVENT = "reject_pending_event"
SERVICE_APPROVE_PENDING_EVENT = "approve_pending_event"
SERVICE_RESOLVE_PENDING_EVENT = "resolve_pending_event"
ATTR_TEXT = "text"
ATTR_FILE_ID = "file_id"
ATTR_SOURCE_ID = "source_id"
ATTR_PENDING_ID = "pending_id"
ATTR_EVENT_ID = "event_id"

CONF_EMAIL_ENABLED = "email_enabled"
CONF_EMAIL_HOST = "email_host"
CONF_EMAIL_PORT = "email_port"
CONF_EMAIL_USERNAME = "email_username"
CONF_EMAIL_PASSWORD = "email_password"
CONF_EMAIL_MAILBOX = "email_mailbox"
CONF_EMAIL_VERIFY_SSL = "email_verify_ssl"
