"""Constants for Daylight Calendar Import."""

DOMAIN = "daylight_calendar_import"
CONF_AI_TASK_ENTITY = "ai_task_entity"
CONF_CALENDAR_ENTITY = "calendar_entity"
SERVICE_PARSE_TEXT = "parse_text"
SERVICE_IMPORT_TEXT = "import_text"
SERVICE_SUBMIT_TEXT = "submit_text"
SERVICE_APPROVE_PENDING = "approve_pending"
SERVICE_REJECT_PENDING = "reject_pending"
SERVICE_LIST_PENDING = "list_pending"
SERVICE_GET_PENDING = "get_pending"
SERVICE_GET_PENDING_EVENT = "get_pending_event"
SERVICE_EDIT_PENDING_EVENT = "edit_pending_event"
SERVICE_REJECT_PENDING_EVENT = "reject_pending_event"
SERVICE_APPROVE_PENDING_EVENT = "approve_pending_event"
SERVICE_RESOLVE_PENDING_EVENT = "resolve_pending_event"
ATTR_TEXT = "text"
ATTR_SOURCE_ID = "source_id"
ATTR_PENDING_ID = "pending_id"
ATTR_EVENT_ID = "event_id"
