name: HACS Validation

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate-hacs:
    runs-on: "ubuntu-latest"
    steps:
      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "integration"
          comment: false

  validate-hassfest:
    name: Hassfest validation
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v5
      - name: Hassfest validation
        uses: home-assistant/actions/hassfest@master
